language: python
os: windows
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
script:
  - pytest
notifications:
  email:
    recipients:
    - zfaddi@umassd.edu
    on_success: always
    on_failure: always
