language: python
sudo: required
dist: trusty
cache:
  - pip
  - directories:
      - ~/cache
      - $HOME/.pyenv/cache
      - Library/Caches/Homebrew
addons:
  apt:
    packages:
    # Should you ever need to run tests on linux; these packages are
    # required for testing PyQT5 applications on Ubuntu.
    - x11-utils
    - libxkbcommon-x11-0

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest pytest-qt
  - easy_install distribute
  - pip install -r requirements.txt

matrix:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      env: TOXENV=py36
      dist: xenial          # required for Python >= 3.7
      install:
        - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
        - sudo apt-get update
        - sudo apt install python-pyqt5
      services:
        - xvfb
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      env: TOXENV=py37
      dist: xenial          # required for Python >= 3.7
      services:
        - xvfb
      before_install:
        - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
        - sudo apt-get update
        - sudo apt install python-pyqt5

    - name: "Python 3.6 on macOS"
      os: osx
      language: generic
      env:
        - MAC_PYTHON_VERSION=3.6.8
        - MAC_PYTHON_OSX_VERSION=10.6
      sudo: required
      install:
        - source ./.travis/osx_setup_python.sh $MAC_PYTHON_VERSION $MAC_PYTHON_OSX_VERSION
        - python --version
        - pip install -e .
        - easy_install distribute
        - pip install -r requirements.txt
        - pip freeze
        - pip install PyQt5
    - name: "Python 3.7 on macOS"
      os: osx
      language: generic       # 'language: python' is an error on Travis CI macOS
      env:
        - MAC_PYTHON_VERSION=3.7.3
        - MAC_PYTHON_OSX_VERSION=10.6
      sudo: required
      install:
        - source ./.travis/osx_setup_python.sh $MAC_PYTHON_VERSION $MAC_PYTHON_OSX_VERSION
        - python --version
        - pip install -e .
        - easy_install distribute
        - pip install -r requirements.txt
        - pip freeze
        - pip install PyQt5
    - name: "Python 3.6 on Windows"
      # if: branch = master
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: minimal       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
      env:
        - TOXENV=py36
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      install:                                                                                  #
        - python --version
        - pip install -e .
        - easy_install distribute
        - pip install -r requirements.txt
        - pip freeze
        - pip install PyQt5
    - name: "Python 3.7 on Windows"
      # if: branch = master
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: minimal       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python --version 3.7.3
      env:
        - TOXENV=py37
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH


script:
  - python setup.py test
  - cd "tests" && pytest -s test_JM.py  #
  - pytest -s test_GM.py                #
  - pytest -s test_GO.py                #
notifications:
  email:
    recipients:
    - zfaddi@umassd.edu
    on_success: always
    on_failure: always