language: python
python:
  - 3.6
  - 3.7
  - 3.8
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
services: xvfb
dist: xenial
install:
  - pip install -r requirements.txt # install package + test dependencies
script:
  - pytest
notifications:
  email:
    recipients:
    - zfaddi@umassd.edu
    on_success: always
    on_failure: always
