language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - sudo apt-get install -qq libegl1-mesa
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
services: xvfb
script:
  - pytest
notifications:
  email:
    recipients:
    - zfaddi@umassd.edu
    on_success: always
    on_failure: always
