language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt # install package + test dependencies
script:
  - cd "tests" && python SFRAT_GUI_Test.py
  - pytest -s test_JM.py
  - pytest -s test_GO.py
notifications:
  email:
    recipients:
    - zfaddi@umassd.edu
    on_success: always
    on_failure: always
